language: android
sudo: false

branches:
  only:
    - master
    
jdk:
  - openjdk7
  
android:
  components:
    - android-25
    - build-tools-25.0.2

script:
  - bash gradlew uploadArchives
  - cd example/TestApplication; sh gradlew testfairyRelease

