language: android
sudo: false

branches:
  only:
    - master
    
jdk:
  - openjdk8
  
android:
  components:
    - android-25
    - build-tools-25.0.2

before_script:
  # workaround for license agreement: https://github.com/travis-ci/travis-ci/issues/6617
  - mkdir -p "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  
script:
  - bash gradlew uploadArchives
  - cd example/TestApplication; bash gradlew testfairyDebug

